2025-07-06 00:36:49 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:36:49 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:36:49 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:36:49 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:36:49 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:36:49 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:36:49 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:36:49 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:36:50 | ERROR    | __main__:get_account:83 - 接口异常: %s
Traceback (most recent call last):

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x1027cc040>
    └ <Thread(Thread-11 (process_request_thread), started daemon 13170143232)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x1027cbd80>
    └ <Thread(Thread-11 (process_request_thread), started daemon 13170143232)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11 (process_request_thread), started daemon 13170143232)>
    │    │        │    └ (<socket.socket fd=27, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53100)>, ('127.0.0.1', 53100))
    │    │        └ <Thread(Thread-11 (process_request_thread), started daemon 13170143232)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>>
    └ <Thread(Thread-11 (process_request_thread), started daemon 13170143232)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 53100)
    │    │              └ <socket.socket fd=27, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53100)>
    │    └ <function BaseServer.finish_request at 0x1027cdda0>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │    │                   │        └ ('127.0.0.1', 53100)
    │    │                   └ <socket.socket fd=27, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53100)>
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x103402ca0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x1070cfe10>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x1031b8180>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x1070cfe10>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 424, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x1070cfe10>>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x1070cfe10>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x1071ab2e0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x1071d0040>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1071aaf20>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=27>, 'wsgi.errors': <_io.TextIOWra...
               │    └ <Flask 'web_app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1071aaf20>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=27>, 'wsgi.errors': <_io.TextIOWra...
           │    └ <function Flask.wsgi_app at 0x103f28e00>
           └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x103f28540>
               └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x103f284a0>
         └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'get_account'
           │    │           │    │              └ <Rule '/api/account' (GET, OPTIONS, HEAD) -> get_account>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x107097920>, 'index': <function index at 0x1070b5440>, 'get_account...
           │    │           └ <Flask 'web_app'>
           │    └ <function Flask.ensure_sync at 0x103f28720>
           └ <Flask 'web_app'>

> File "/Users/dujian/aster/aster_bot_python/web_app.py", line 65, in get_account
    account = ex.get_account()
              │  └ <function Aster.get_account at 0x1043684a0>
              └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 602, in get_account
    response = self._signed_request('GET', '/fapi/v2/account')
               │    └ <function Aster._signed_request at 0x104353c40>
               └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 419, in _signed_request
    raise Exception(f"API请求失败: {response.status_code} - {response.text}")
                                │        │               │        └ <property object at 0x104348590>
                                │        │               └ <Response [400]>
                                │        └ 400
                                └ <Response [400]>

Exception: API请求失败: 400 - {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2025-07-06 00:36:50 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:36:50 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:36:50 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:36:50 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:36:51 | ERROR    | __main__:get_account:83 - 接口异常: %s
Traceback (most recent call last):

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x1027cc040>
    └ <Thread(Thread-12 (process_request_thread), started daemon 6271234048)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x1027cbd80>
    └ <Thread(Thread-12 (process_request_thread), started daemon 6271234048)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-12 (process_request_thread), started daemon 6271234048)>
    │    │        │    └ (<socket.socket fd=24, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53114)>, ('127.0.0.1', 53114))
    │    │        └ <Thread(Thread-12 (process_request_thread), started daemon 6271234048)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>>
    └ <Thread(Thread-12 (process_request_thread), started daemon 6271234048)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 53114)
    │    │              └ <socket.socket fd=24, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53114)>
    │    └ <function BaseServer.finish_request at 0x1027cdda0>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │    │                   │        └ ('127.0.0.1', 53114)
    │    │                   └ <socket.socket fd=24, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53114)>
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x103402ca0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x1070cf230>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x1031b8180>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x1070cf230>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 424, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x1070cf230>>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x1070cf230>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x1071ab2e0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x1070cf350>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1071aaf20>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=24>, 'wsgi.errors': <_io.TextIOWra...
               │    └ <Flask 'web_app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1071aaf20>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=24>, 'wsgi.errors': <_io.TextIOWra...
           │    └ <function Flask.wsgi_app at 0x103f28e00>
           └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x103f28540>
               └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x103f284a0>
         └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'get_account'
           │    │           │    │              └ <Rule '/api/account' (GET, OPTIONS, HEAD) -> get_account>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x107097920>, 'index': <function index at 0x1070b5440>, 'get_account...
           │    │           └ <Flask 'web_app'>
           │    └ <function Flask.ensure_sync at 0x103f28720>
           └ <Flask 'web_app'>

> File "/Users/dujian/aster/aster_bot_python/web_app.py", line 65, in get_account
    account = ex.get_account()
              │  └ <function Aster.get_account at 0x1043684a0>
              └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 602, in get_account
    response = self._signed_request('GET', '/fapi/v2/account')
               │    └ <function Aster._signed_request at 0x104353c40>
               └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 419, in _signed_request
    raise Exception(f"API请求失败: {response.status_code} - {response.text}")
                                │        │               │        └ <property object at 0x104348590>
                                │        │               └ <Response [400]>
                                │        └ 400
                                └ <Response [400]>

Exception: API请求失败: 400 - {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2025-07-06 00:36:51 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:36:51 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:36:51 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:36:51 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:36:52 | ERROR    | __main__:get_account:83 - 接口异常: %s
Traceback (most recent call last):

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x1027cc040>
    └ <Thread(Thread-13 (process_request_thread), started daemon 13170143232)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x1027cbd80>
    └ <Thread(Thread-13 (process_request_thread), started daemon 13170143232)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-13 (process_request_thread), started daemon 13170143232)>
    │    │        │    └ (<socket.socket fd=27, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53118)>, ('127.0.0.1', 53118))
    │    │        └ <Thread(Thread-13 (process_request_thread), started daemon 13170143232)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>>
    └ <Thread(Thread-13 (process_request_thread), started daemon 13170143232)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 53118)
    │    │              └ <socket.socket fd=27, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53118)>
    │    └ <function BaseServer.finish_request at 0x1027cdda0>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │    │                   │        └ ('127.0.0.1', 53118)
    │    │                   └ <socket.socket fd=27, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53118)>
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x103402ca0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10713ae70>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x1031b8180>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10713ae70>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 424, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x10713ae70>>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x10713ae70>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x107185440>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x1071d1470>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x107185300>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=27>, 'wsgi.errors': <_io.TextIOWra...
               │    └ <Flask 'web_app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x107185300>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=27>, 'wsgi.errors': <_io.TextIOWra...
           │    └ <function Flask.wsgi_app at 0x103f28e00>
           └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x103f28540>
               └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x103f284a0>
         └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'get_account'
           │    │           │    │              └ <Rule '/api/account' (GET, OPTIONS, HEAD) -> get_account>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x107097920>, 'index': <function index at 0x1070b5440>, 'get_account...
           │    │           └ <Flask 'web_app'>
           │    └ <function Flask.ensure_sync at 0x103f28720>
           └ <Flask 'web_app'>

> File "/Users/dujian/aster/aster_bot_python/web_app.py", line 65, in get_account
    account = ex.get_account()
              │  └ <function Aster.get_account at 0x1043684a0>
              └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 602, in get_account
    response = self._signed_request('GET', '/fapi/v2/account')
               │    └ <function Aster._signed_request at 0x104353c40>
               └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 419, in _signed_request
    raise Exception(f"API请求失败: {response.status_code} - {response.text}")
                                │        │               │        └ <property object at 0x104348590>
                                │        │               └ <Response [400]>
                                │        └ 400
                                └ <Response [400]>

Exception: API请求失败: 400 - {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2025-07-06 00:36:52 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:36:52 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:36:52 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:36:52 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:36:53 | ERROR    | __main__:get_account:83 - 接口异常: %s
Traceback (most recent call last):

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x1027cc040>
    └ <Thread(Thread-15 (process_request_thread), started daemon 6288060416)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x1027cbd80>
    └ <Thread(Thread-15 (process_request_thread), started daemon 6288060416)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-15 (process_request_thread), started daemon 6288060416)>
    │    │        │    └ (<socket.socket fd=24, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53130)>, ('127.0.0.1', 53130))
    │    │        └ <Thread(Thread-15 (process_request_thread), started daemon 6288060416)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>>
    └ <Thread(Thread-15 (process_request_thread), started daemon 6288060416)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 53130)
    │    │              └ <socket.socket fd=24, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53130)>
    │    └ <function BaseServer.finish_request at 0x1027cdda0>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │    │                   │        └ ('127.0.0.1', 53130)
    │    │                   └ <socket.socket fd=24, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53130)>
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x103402ca0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x107119590>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x1031b8180>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x107119590>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 424, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x107119590>>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x107119590>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x107167920>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x1070cfe00>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x107167380>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=24>, 'wsgi.errors': <_io.TextIOWra...
               │    └ <Flask 'web_app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x107167380>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=24>, 'wsgi.errors': <_io.TextIOWra...
           │    └ <function Flask.wsgi_app at 0x103f28e00>
           └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x103f28540>
               └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x103f284a0>
         └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'get_account'
           │    │           │    │              └ <Rule '/api/account' (GET, OPTIONS, HEAD) -> get_account>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x107097920>, 'index': <function index at 0x1070b5440>, 'get_account...
           │    │           └ <Flask 'web_app'>
           │    └ <function Flask.ensure_sync at 0x103f28720>
           └ <Flask 'web_app'>

> File "/Users/dujian/aster/aster_bot_python/web_app.py", line 65, in get_account
    account = ex.get_account()
              │  └ <function Aster.get_account at 0x1043684a0>
              └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 602, in get_account
    response = self._signed_request('GET', '/fapi/v2/account')
               │    └ <function Aster._signed_request at 0x104353c40>
               └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 419, in _signed_request
    raise Exception(f"API请求失败: {response.status_code} - {response.text}")
                                │        │               │        └ <property object at 0x104348590>
                                │        │               └ <Response [400]>
                                │        └ 400
                                └ <Response [400]>

Exception: API请求失败: 400 - {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2025-07-06 00:37:02 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:37:02 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:37:02 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:37:02 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:37:09 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:37:09 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:37:09 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:37:09 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:37:12 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:37:12 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:37:12 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:37:12 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:37:13 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:37:13 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:37:13 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:37:13 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:37:49 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:37:49 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:37:49 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:37:49 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:37:49 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:37:49 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:37:49 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:37:49 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:37:50 | ERROR    | __main__:get_account:83 - 接口异常: %s
Traceback (most recent call last):

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x1027cc040>
    └ <Thread(Thread-23 (process_request_thread), started daemon 13438578688)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x1027cbd80>
    └ <Thread(Thread-23 (process_request_thread), started daemon 13438578688)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-23 (process_request_thread), started daemon 13438578688)>
    │    │        │    └ (<socket.socket fd=26, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53382)>, ('127.0.0.1', 53382))
    │    │        └ <Thread(Thread-23 (process_request_thread), started daemon 13438578688)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>>
    └ <Thread(Thread-23 (process_request_thread), started daemon 13438578688)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 53382)
    │    │              └ <socket.socket fd=26, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53382)>
    │    └ <function BaseServer.finish_request at 0x1027cdda0>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │    │                   │        └ ('127.0.0.1', 53382)
    │    │                   └ <socket.socket fd=26, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53382)>
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x103402ca0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x1071d0050>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x1031b8180>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x1071d0050>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 424, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x1071d0050>>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x1071d0050>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x1071ab100>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x1070cefc0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1071aaa20>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=26>, 'wsgi.errors': <_io.TextIOWra...
               │    └ <Flask 'web_app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1071aaa20>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=26>, 'wsgi.errors': <_io.TextIOWra...
           │    └ <function Flask.wsgi_app at 0x103f28e00>
           └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x103f28540>
               └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x103f284a0>
         └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'get_account'
           │    │           │    │              └ <Rule '/api/account' (GET, OPTIONS, HEAD) -> get_account>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x107097920>, 'index': <function index at 0x1070b5440>, 'get_account...
           │    │           └ <Flask 'web_app'>
           │    └ <function Flask.ensure_sync at 0x103f28720>
           └ <Flask 'web_app'>

> File "/Users/dujian/aster/aster_bot_python/web_app.py", line 65, in get_account
    account = ex.get_account()
              │  └ <function Aster.get_account at 0x1043684a0>
              └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 602, in get_account
    response = self._signed_request('GET', '/fapi/v2/account')
               │    └ <function Aster._signed_request at 0x104353c40>
               └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 419, in _signed_request
    raise Exception(f"API请求失败: {response.status_code} - {response.text}")
                                │        │               │        └ <property object at 0x104348590>
                                │        │               └ <Response [400]>
                                │        └ 400
                                └ <Response [400]>

Exception: API请求失败: 400 - {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2025-07-06 00:37:50 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:37:50 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:37:50 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:37:50 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:37:51 | ERROR    | __main__:get_account:83 - 接口异常: %s
Traceback (most recent call last):

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x1027cc040>
    └ <Thread(Thread-24 (process_request_thread), started daemon 6271234048)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x1027cbd80>
    └ <Thread(Thread-24 (process_request_thread), started daemon 6271234048)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-24 (process_request_thread), started daemon 6271234048)>
    │    │        │    └ (<socket.socket fd=25, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53397)>, ('127.0.0.1', 53397))
    │    │        └ <Thread(Thread-24 (process_request_thread), started daemon 6271234048)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>>
    └ <Thread(Thread-24 (process_request_thread), started daemon 6271234048)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 53397)
    │    │              └ <socket.socket fd=25, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53397)>
    │    └ <function BaseServer.finish_request at 0x1027cdda0>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │    │                   │        └ ('127.0.0.1', 53397)
    │    │                   └ <socket.socket fd=25, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53397)>
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x103402ca0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10713f860>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x1031b8180>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10713f860>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 424, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x10713f860>>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x10713f860>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x1071ab100>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x1070cefc0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1071ab6a0>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=25>, 'wsgi.errors': <_io.TextIOWra...
               │    └ <Flask 'web_app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1071ab6a0>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=25>, 'wsgi.errors': <_io.TextIOWra...
           │    └ <function Flask.wsgi_app at 0x103f28e00>
           └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x103f28540>
               └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x103f284a0>
         └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'get_account'
           │    │           │    │              └ <Rule '/api/account' (GET, OPTIONS, HEAD) -> get_account>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x107097920>, 'index': <function index at 0x1070b5440>, 'get_account...
           │    │           └ <Flask 'web_app'>
           │    └ <function Flask.ensure_sync at 0x103f28720>
           └ <Flask 'web_app'>

> File "/Users/dujian/aster/aster_bot_python/web_app.py", line 65, in get_account
    account = ex.get_account()
              │  └ <function Aster.get_account at 0x1043684a0>
              └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 602, in get_account
    response = self._signed_request('GET', '/fapi/v2/account')
               │    └ <function Aster._signed_request at 0x104353c40>
               └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 419, in _signed_request
    raise Exception(f"API请求失败: {response.status_code} - {response.text}")
                                │        │               │        └ <property object at 0x104348590>
                                │        │               └ <Response [400]>
                                │        └ 400
                                └ <Response [400]>

Exception: API请求失败: 400 - {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2025-07-06 00:37:51 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:37:51 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:37:51 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:37:51 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:37:52 | ERROR    | __main__:get_account:83 - 接口异常: %s
Traceback (most recent call last):

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x1027cc040>
    └ <Thread(Thread-25 (process_request_thread), started daemon 13438578688)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x1027cbd80>
    └ <Thread(Thread-25 (process_request_thread), started daemon 13438578688)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-25 (process_request_thread), started daemon 13438578688)>
    │    │        │    └ (<socket.socket fd=28, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53405)>, ('127.0.0.1', 53405))
    │    │        └ <Thread(Thread-25 (process_request_thread), started daemon 13438578688)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>>
    └ <Thread(Thread-25 (process_request_thread), started daemon 13438578688)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 53405)
    │    │              └ <socket.socket fd=28, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53405)>
    │    └ <function BaseServer.finish_request at 0x1027cdda0>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │    │                   │        └ ('127.0.0.1', 53405)
    │    │                   └ <socket.socket fd=28, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53405)>
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x103402ca0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10713fad0>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x1031b8180>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10713fad0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 424, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x10713fad0>>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x10713fad0>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x1072b5940>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x1070cf220>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1072b4360>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=28>, 'wsgi.errors': <_io.TextIOWra...
               │    └ <Flask 'web_app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1072b4360>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=28>, 'wsgi.errors': <_io.TextIOWra...
           │    └ <function Flask.wsgi_app at 0x103f28e00>
           └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x103f28540>
               └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x103f284a0>
         └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'get_account'
           │    │           │    │              └ <Rule '/api/account' (GET, OPTIONS, HEAD) -> get_account>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x107097920>, 'index': <function index at 0x1070b5440>, 'get_account...
           │    │           └ <Flask 'web_app'>
           │    └ <function Flask.ensure_sync at 0x103f28720>
           └ <Flask 'web_app'>

> File "/Users/dujian/aster/aster_bot_python/web_app.py", line 65, in get_account
    account = ex.get_account()
              │  └ <function Aster.get_account at 0x1043684a0>
              └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 602, in get_account
    response = self._signed_request('GET', '/fapi/v2/account')
               │    └ <function Aster._signed_request at 0x104353c40>
               └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 419, in _signed_request
    raise Exception(f"API请求失败: {response.status_code} - {response.text}")
                                │        │               │        └ <property object at 0x104348590>
                                │        │               └ <Response [400]>
                                │        └ 400
                                └ <Response [400]>

Exception: API请求失败: 400 - {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2025-07-06 00:37:52 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:37:52 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:37:52 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:37:52 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:37:53 | ERROR    | __main__:get_account:83 - 接口异常: %s
Traceback (most recent call last):

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x1027cc040>
    └ <Thread(Thread-27 (process_request_thread), started daemon 6288060416)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x1027cbd80>
    └ <Thread(Thread-27 (process_request_thread), started daemon 6288060416)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-27 (process_request_thread), started daemon 6288060416)>
    │    │        │    └ (<socket.socket fd=25, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53417)>, ('127.0.0.1', 53417))
    │    │        └ <Thread(Thread-27 (process_request_thread), started daemon 6288060416)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>>
    └ <Thread(Thread-27 (process_request_thread), started daemon 6288060416)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 53417)
    │    │              └ <socket.socket fd=25, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53417)>
    │    └ <function BaseServer.finish_request at 0x1027cdda0>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │    │                   │        └ ('127.0.0.1', 53417)
    │    │                   └ <socket.socket fd=25, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53417)>
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x103402ca0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10713f860>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x1031b8180>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10713f860>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 424, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x10713f860>>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x10713f860>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x107185300>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x1070cfcd0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1071abce0>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=25>, 'wsgi.errors': <_io.TextIOWra...
               │    └ <Flask 'web_app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1071abce0>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=25>, 'wsgi.errors': <_io.TextIOWra...
           │    └ <function Flask.wsgi_app at 0x103f28e00>
           └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x103f28540>
               └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x103f284a0>
         └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'get_account'
           │    │           │    │              └ <Rule '/api/account' (GET, OPTIONS, HEAD) -> get_account>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x107097920>, 'index': <function index at 0x1070b5440>, 'get_account...
           │    │           └ <Flask 'web_app'>
           │    └ <function Flask.ensure_sync at 0x103f28720>
           └ <Flask 'web_app'>

> File "/Users/dujian/aster/aster_bot_python/web_app.py", line 65, in get_account
    account = ex.get_account()
              │  └ <function Aster.get_account at 0x1043684a0>
              └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 602, in get_account
    response = self._signed_request('GET', '/fapi/v2/account')
               │    └ <function Aster._signed_request at 0x104353c40>
               └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 419, in _signed_request
    raise Exception(f"API请求失败: {response.status_code} - {response.text}")
                                │        │               │        └ <property object at 0x104348590>
                                │        │               └ <Response [400]>
                                │        └ 400
                                └ <Response [400]>

Exception: API请求失败: 400 - {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2025-07-06 00:38:02 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:38:02 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:38:02 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:38:02 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:38:09 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:38:09 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:38:09 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:38:09 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:38:12 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:38:12 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:38:12 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:38:12 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:38:13 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:38:13 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:38:13 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:38:13 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:38:49 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:38:49 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:38:49 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:38:49 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:38:49 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:38:49 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:38:49 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:38:49 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:38:50 | ERROR    | __main__:get_account:83 - 接口异常: %s
Traceback (most recent call last):

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x1027cc040>
    └ <Thread(Thread-35 (process_request_thread), started daemon 13438578688)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x1027cbd80>
    └ <Thread(Thread-35 (process_request_thread), started daemon 13438578688)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-35 (process_request_thread), started daemon 13438578688)>
    │    │        │    └ (<socket.socket fd=25, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53734)>, ('127.0.0.1', 53734))
    │    │        └ <Thread(Thread-35 (process_request_thread), started daemon 13438578688)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>>
    └ <Thread(Thread-35 (process_request_thread), started daemon 13438578688)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 53734)
    │    │              └ <socket.socket fd=25, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53734)>
    │    └ <function BaseServer.finish_request at 0x1027cdda0>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │    │                   │        └ ('127.0.0.1', 53734)
    │    │                   └ <socket.socket fd=25, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53734)>
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x103402ca0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x1071d0940>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x1031b8180>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x1071d0940>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 424, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x1071d0940>>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x1071d0940>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x1072b5620>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x1070cf350>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1072b5c60>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=25>, 'wsgi.errors': <_io.TextIOWra...
               │    └ <Flask 'web_app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x1072b5c60>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=25>, 'wsgi.errors': <_io.TextIOWra...
           │    └ <function Flask.wsgi_app at 0x103f28e00>
           └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x103f28540>
               └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x103f284a0>
         └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'get_account'
           │    │           │    │              └ <Rule '/api/account' (GET, OPTIONS, HEAD) -> get_account>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x107097920>, 'index': <function index at 0x1070b5440>, 'get_account...
           │    │           └ <Flask 'web_app'>
           │    └ <function Flask.ensure_sync at 0x103f28720>
           └ <Flask 'web_app'>

> File "/Users/dujian/aster/aster_bot_python/web_app.py", line 65, in get_account
    account = ex.get_account()
              │  └ <function Aster.get_account at 0x1043684a0>
              └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 602, in get_account
    response = self._signed_request('GET', '/fapi/v2/account')
               │    └ <function Aster._signed_request at 0x104353c40>
               └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 419, in _signed_request
    raise Exception(f"API请求失败: {response.status_code} - {response.text}")
                                │        │               │        └ <property object at 0x104348590>
                                │        │               └ <Response [400]>
                                │        └ 400
                                └ <Response [400]>

Exception: API请求失败: 400 - {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2025-07-06 00:38:50 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:38:50 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:38:50 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:38:50 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:38:51 | ERROR    | __main__:get_account:83 - 接口异常: %s
Traceback (most recent call last):

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x1027cc040>
    └ <Thread(Thread-36 (process_request_thread), started daemon 13455405056)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x1027cbd80>
    └ <Thread(Thread-36 (process_request_thread), started daemon 13455405056)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-36 (process_request_thread), started daemon 13455405056)>
    │    │        │    └ (<socket.socket fd=30, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53749)>, ('127.0.0.1', 53749))
    │    │        └ <Thread(Thread-36 (process_request_thread), started daemon 13455405056)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>>
    └ <Thread(Thread-36 (process_request_thread), started daemon 13455405056)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 53749)
    │    │              └ <socket.socket fd=30, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53749)>
    │    └ <function BaseServer.finish_request at 0x1027cdda0>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │    │                   │        └ ('127.0.0.1', 53749)
    │    │                   └ <socket.socket fd=30, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53749)>
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x103402ca0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10713f520>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x1031b8180>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10713f520>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 424, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x10713f520>>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x10713f520>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x107185ee0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x1070cf810>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x107185da0>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=30>, 'wsgi.errors': <_io.TextIOWra...
               │    └ <Flask 'web_app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x107185da0>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=30>, 'wsgi.errors': <_io.TextIOWra...
           │    └ <function Flask.wsgi_app at 0x103f28e00>
           └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x103f28540>
               └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x103f284a0>
         └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'get_account'
           │    │           │    │              └ <Rule '/api/account' (GET, OPTIONS, HEAD) -> get_account>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x107097920>, 'index': <function index at 0x1070b5440>, 'get_account...
           │    │           └ <Flask 'web_app'>
           │    └ <function Flask.ensure_sync at 0x103f28720>
           └ <Flask 'web_app'>

> File "/Users/dujian/aster/aster_bot_python/web_app.py", line 65, in get_account
    account = ex.get_account()
              │  └ <function Aster.get_account at 0x1043684a0>
              └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 602, in get_account
    response = self._signed_request('GET', '/fapi/v2/account')
               │    └ <function Aster._signed_request at 0x104353c40>
               └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 419, in _signed_request
    raise Exception(f"API请求失败: {response.status_code} - {response.text}")
                                │        │               │        └ <property object at 0x104348590>
                                │        │               └ <Response [400]>
                                │        └ 400
                                └ <Response [400]>

Exception: API请求失败: 400 - {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2025-07-06 00:38:51 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:38:51 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:38:51 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:38:51 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:38:52 | ERROR    | __main__:get_account:83 - 接口异常: %s
Traceback (most recent call last):

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x1027cc040>
    └ <Thread(Thread-37 (process_request_thread), started daemon 6271234048)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x1027cbd80>
    └ <Thread(Thread-37 (process_request_thread), started daemon 6271234048)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-37 (process_request_thread), started daemon 6271234048)>
    │    │        │    └ (<socket.socket fd=22, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53756)>, ('127.0.0.1', 53756))
    │    │        └ <Thread(Thread-37 (process_request_thread), started daemon 6271234048)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>>
    └ <Thread(Thread-37 (process_request_thread), started daemon 6271234048)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 53756)
    │    │              └ <socket.socket fd=22, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53756)>
    │    └ <function BaseServer.finish_request at 0x1027cdda0>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │    │                   │        └ ('127.0.0.1', 53756)
    │    │                   └ <socket.socket fd=22, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53756)>
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x103402ca0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10713f520>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x1031b8180>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10713f520>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 424, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x10713f520>>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x10713f520>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x1043d00e0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x1070cf810>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x107185da0>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=22>, 'wsgi.errors': <_io.TextIOWra...
               │    └ <Flask 'web_app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x107185da0>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=22>, 'wsgi.errors': <_io.TextIOWra...
           │    └ <function Flask.wsgi_app at 0x103f28e00>
           └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x103f28540>
               └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x103f284a0>
         └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'get_account'
           │    │           │    │              └ <Rule '/api/account' (GET, OPTIONS, HEAD) -> get_account>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x107097920>, 'index': <function index at 0x1070b5440>, 'get_account...
           │    │           └ <Flask 'web_app'>
           │    └ <function Flask.ensure_sync at 0x103f28720>
           └ <Flask 'web_app'>

> File "/Users/dujian/aster/aster_bot_python/web_app.py", line 65, in get_account
    account = ex.get_account()
              │  └ <function Aster.get_account at 0x1043684a0>
              └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 602, in get_account
    response = self._signed_request('GET', '/fapi/v2/account')
               │    └ <function Aster._signed_request at 0x104353c40>
               └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 419, in _signed_request
    raise Exception(f"API请求失败: {response.status_code} - {response.text}")
                                │        │               │        └ <property object at 0x104348590>
                                │        │               └ <Response [400]>
                                │        └ 400
                                └ <Response [400]>

Exception: API请求失败: 400 - {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
2025-07-06 00:38:52 | INFO     | __main__:get_account:44 - 收到的exchange参数: %s
2025-07-06 00:38:52 | INFO     | __main__:get_account:46 - ex实例类型: %s
2025-07-06 00:38:52 | INFO     | __main__:get_account:48 - web_app.py用的BACKPACK_API_KEY: %s
2025-07-06 00:38:52 | INFO     | __main__:get_account:49 - web_app.py用的BACKPACK_API_SECRET: %s
2025-07-06 00:38:52 | ERROR    | __main__:get_account:83 - 接口异常: %s
Traceback (most recent call last):

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1012, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x1027cc040>
    └ <Thread(Thread-39 (process_request_thread), started daemon 6288060416)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 1041, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x1027cbd80>
    └ <Thread(Thread-39 (process_request_thread), started daemon 6288060416)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-39 (process_request_thread), started daemon 6288060416)>
    │    │        │    └ (<socket.socket fd=25, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53777)>, ('127.0.0.1', 53777))
    │    │        └ <Thread(Thread-39 (process_request_thread), started daemon 6288060416)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>>
    └ <Thread(Thread-39 (process_request_thread), started daemon 6288060416)>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 53777)
    │    │              └ <socket.socket fd=25, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53777)>
    │    └ <function BaseServer.finish_request at 0x1027cdda0>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │    │                   │        └ ('127.0.0.1', 53777)
    │    │                   └ <socket.socket fd=25, family=2, type=1, proto=0, laddr=('127.0.0.1', 5001), raddr=('127.0.0.1', 53777)>
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/socketserver.py", line 766, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x103402ca0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10713e680>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 398, in handle
    super().handle()

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 436, in handle
    self.handle_one_request()
    │    └ <function BaseHTTPRequestHandler.handle_one_request at 0x1031b8180>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x10713e680>

  File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/http/server.py", line 424, in handle_one_request
    method()
    └ <bound method WSGIRequestHandler.run_wsgi of <werkzeug.serving.WSGIRequestHandler object at 0x10713e680>>

  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 370, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x1070ab4d0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x10713e680>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x1072b6700>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/serving.py", line 333, in execute
    for data in application_iter:
                └ <generator object DebuggedApplication.debug_application at 0x1070cf810>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/werkzeug/debug/__init__.py", line 343, in debug_application
    app_iter = self.app(environ, start_response)
               │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x107167920>
               │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=25>, 'wsgi.errors': <_io.TextIOWra...
               │    └ <Flask 'web_app'>
               └ <werkzeug.debug.DebuggedApplication object at 0x1070a9fd0>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x107167920>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=25>, 'wsgi.errors': <_io.TextIOWra...
           │    └ <function Flask.wsgi_app at 0x103f28e00>
           └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x103f28540>
               └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x103f284a0>
         └ <Flask 'web_app'>
  File "/Users/dujian/aster/aster_bot_python/venv/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           │    │           │    │              │    │            └ {}
           │    │           │    │              │    └ 'get_account'
           │    │           │    │              └ <Rule '/api/account' (GET, OPTIONS, HEAD) -> get_account>
           │    │           │    └ {'static': <function Flask.__init__.<locals>.<lambda> at 0x107097920>, 'index': <function index at 0x1070b5440>, 'get_account...
           │    │           └ <Flask 'web_app'>
           │    └ <function Flask.ensure_sync at 0x103f28720>
           └ <Flask 'web_app'>

> File "/Users/dujian/aster/aster_bot_python/web_app.py", line 65, in get_account
    account = ex.get_account()
              │  └ <function Aster.get_account at 0x1043684a0>
              └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 602, in get_account
    response = self._signed_request('GET', '/fapi/v2/account')
               │    └ <function Aster._signed_request at 0x104353c40>
               └ <exchanges.aster.Aster object at 0x1070b07d0>

  File "/Users/dujian/aster/aster_bot_python/exchanges/aster.py", line 419, in _signed_request
    raise Exception(f"API请求失败: {response.status_code} - {response.text}")
                                │        │               │        └ <property object at 0x104348590>
                                │        │               └ <Response [400]>
                                │        └ 400
                                └ <Response [400]>

Exception: API请求失败: 400 - {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}
